### ISSUE TITLE
Having issues with include tags using markdown files

### ISSUE THREAD

**Issue by JessJodoin** [JessJodoin/portfolio#1]
Hey @thomasjbradley

I was wondering if you could help me a bit 😄 

I have my markdown files for each case study done, and I tried using include tags similar to this `{{include.data.mockup-3}} ` but nothing shows up in my pattern library. I'm going to assume I forgot to do something or I did it wrong (lol)
Could you take a quick peek and let me know?

Thanks!!

**Comment by JessJodoin** [comment]
Also now this is happening... so fun 🙃 

<img width="925" alt="Screen Shot 2020-10-21 at 8 10 39 PM" src="https://user-images.githubusercontent.com/43217543/96803197-98f5ab00-13d9-11eb-8711-45cf19d3cb3b.png">

**Comment by thomasjbradley** [comment]
*Re: error—* Have you hosted your website on Netflify? GitHub hosting doesn’t support advanced features like Patternbot.

**Comment by thomasjbradley** [comment]
*Re: MD—* The first thing I see is that each MD file is missing the `---` at the bottom, after all of the front matter data. I can see it at the top, but needs to be on the bottom too.

**Comment by JessJodoin** [comment]
And I can add my custom domain to netlify?
Also does that mean I change the CNAME on cloudflare from my github link to the auto-generated domain the netlify gives me?

**Comment by thomasjbradley** [comment]
> And I can add my custom domain to netlify?

Yes, totally.

> Also does that mean I change the CNAME on cloudflare from my github link to the auto-generated domain the netlify gives me?

Exactly correct!

**Comment by JessJodoin** [comment]
Okay one last question (hopefully) and I'll quit bugging you

How do I go about adding a custom SSL certificate to my netlify? 
<img width="949" alt="Screen Shot 2020-10-22 at 11 17 32 AM" src="https://user-images.githubusercontent.com/43217543/96893228-7d7db500-1458-11eb-941c-a49c74cb2c5a.png">

Cause I followed the web 5 hosting lesson so I'm using Cloudflare, so I'm not quite sure how to find the certificate so I can add it to netlify

Or I guess a better question is should I just ignore it, and change the settings in Cloudflare to _always use https_

**Comment by thomasjbradley** [comment]
That is generating a certificate for you—you just have to give it some time.
After it’s working you can turn on “Always use HTTPS”.
