### ISSUE TITLE
The data includes are still sucky and a quick question about SEO stuff

### ISSUE THREAD

**Issue by JessJodoin** [JessJodoin/portfolio#2]
Hey @thomasjbradley

It's me again lol (also here's a link to my pattern library https://jessjodoin.ca/pattern-library/#brand )

I add the `---` at the bottom of each markdown file but still no change. I still don't see the content where I included the `{{include.data.}}`
I'm not sure how to fix that 😞 

Also about SEO stuff. On each of my pages I have a unique title and a meta tag with a unique description. So what I'm wondering is how do I add unique titles and meta descriptions for my project case studies? Do I add something to their markdown files? Or do I add something to the top of the case-study.html layout?

**Comment by thomasjbradley** [comment]
Your pattern library looks so amazing!!! I’m so excited to see you using it! (I’m beaming with proud-ness right now! 😊)

*Re: include—* What file are you using `{{include.data.}}`—I couldn’t find it in the obvious-to-me places?

*Re: SEO—* You’ve got it all set up properly, and as you suggested, it’s a simple as adding the `title` & `description` into each case study. Add these two lines into each case-study MD file:

https://github.com/JessJodoin/portfolio/blob/master/about.html#L3-L4

**Comment by JessJodoin** [comment]
The includes are used in most of my sections and the cast study banner (I removed them for a bit so I could style each thing, sorry. I put them back now though lol)

Also, in my project text section, I have a `<ul>` for the project deliverables that I want to populate with the markdown file stuff but I'm not sure how I go about doing that. 

Also also, I use my side card section for regular content (currently just using regular includes) but I also want to use it on my case study pages (which would mean using the `{{include.data.}}`) can I do both or should I duplicate it and make on with regular includes and the other with `{{include.data.}}`?

**Comment by thomasjbradley** [comment]
*Re: includes—*

It’s how you’ve labeled them inside the `_config.yml` file:
https://github.com/JessJodoin/portfolio/blob/master/_config.yml#L31
That line needs to match the folder name, so it should be `projects:` not `case-study:`—then I think everything will connect together. Don’t forget to stop and start in Terminal.

**Comment by thomasjbradley** [comment]
*Re: ul—* 

In the Markdown file, you’d create a list like this:

```md
deliverables:
  - PSD
  - Website
  - Banner ad
```

Then in the HTML/pattern file you could loop over them, like this:

```liquid
<ul>
  {% for del in include.data.deliverables %}
    <li>{{del}}</li>
  {% endfor %}
</ul>
```

**Comment by thomasjbradley** [comment]
*Re: side-card—*

You can use it for both, it just kinda depends on how & where you want to implement it.

You could do something like this:

```liquid
{% include patterns/side-card-section title="Challenges" content=page.challenges %}
```
(Where `page` represents the MD file in this situation.)
But, it completely depends on where you put that include & how you plan on integrating it into your layout.

**Comment by JessJodoin** [comment]
I use it on my about page (so I don't have markdown for that... but maybe I should? I've been lazy and been using the regular include tags and using the config.yml fields to populate it) and then on each case study page with the markdown file info.

I’m also having a struggle time making my cards. Cards just don’t like me apparently (very reminiscent of my ecommerce website lol). I have it pretty much looking and acting like I want but I can't get the text to centre properly inside the blue `<div>`.

<img width="492" alt="Screen Shot 2020-10-23 at 4 28 00 PM" src="https://user-images.githubusercontent.com/43217543/97051194-be56f600-154c-11eb-8f49-145aadfda4dc.png">

**Comment by JessJodoin** [comment]
For linking the page navigation on my case studies, what do i put after the /projects/

this is what I have for both `<a> `tags, but it doesn't lead anywhere
`<a href="{{site.baseurl}}/projects/{{page.previous}}">`
`<a href="{{site.baseurl}}/projects/{{page.next}}">`

**Comment by thomasjbradley** [comment]
Did you get the cards figured out?

**Comment by JessJodoin** [comment]
Yup! 😄
