### ISSUE TITLE
Linking the Page Navigation and Content Not Showing Up On the Project Pages

### ISSUE THREAD

**Issue by JessJodoin** [JessJodoin/portfolio#3]
Hey @thomasjbradley

I'm having issues with my page navigation for the case study pages and an issue with the includes not putting the content on the case study pages, like the includes works great in my pattern library (all the markdown content is there) but for whatever reason it doesn't show on each case study page.

And for linking the page navigation on my case studies, what do i put after the /projects/
this is what I have for both `<a>` tags, but it doesn't lead anywhere
```
 <a href="{{site.baseurl}}/projects/{{page.previous}}"> 
<a href="{{site.baseurl}}/projects/{{page.next}}">
```

**Comment by thomasjbradley** [comment]
You got this figured out too?

**Comment by JessJodoin** [comment]
Sort of. I couldn't figure out how to get my case study page navigation to loop like I wanted cause I couldn't figure out how to write the else statement to make it work so I just have an if statement that removes the _previous_ from the first case study and the _next_ from the last case study
